### ISSUE TITLE
翻译时，一切格式遵循原文不要更改，本项目的格式是用于生成网站的。

### ISSUE THREAD

**Issue by leviding** [xitu/javascript-tutorial-en#54]
本 Repo 的文件中有一些特殊格式，是作者用于将文件生成在线网站的 flag，如果修改将无法正常生成相应文件，所以要尊重原文。

**Comment by L9m** [comment]
task.md 中的 importance 是不需要翻译的，因为已发布的俄文版也是没有翻译的。

**Comment by leviding** [comment]
importance 统一不翻译

**Comment by jellycsc** [comment]
@leviding 已经 merge 的几篇文章存在排版问题。E.g. [[Link](https://github.com/xitu/javascript-tutorial-en/blob/b65a901d3754e70d23273bdd885a9e41ddb8b1b7/1-js/02-first-steps/04-variables/article.md)]
如果 view 成 markdown 最后一段都在 quotes 里面

**Comment by leviding** [comment]
@jellycsc 都有哪几篇？很多吗

**Comment by jellycsc** [comment]
@leviding 1-js/02-first-steps 第二章节里面好像都有这个问题，后面的我还没看下去

**Comment by leviding** [comment]
@jellycsc ok 的，译文我都对格式做了 review 的，有问题欢迎及时提出方便大家一起及时改进。

**Comment by jellycsc** [comment]
@leviding 那么第二章的那几篇还要改吗？

**Comment by jellycsc** [comment]
@leviding 我理解你的意思了，抱歉，确实是你所说的“无法被 MarkDown 解析”的问题。译文格式和网站保持一致。
